- Ficher source : tco-bus-topologie-pointsarret-td.csv
- Fichier de sorti : stg_star_bus_arrets.csv
- Date de création : 14/11/2025
- Dernière modification : 17/11/2025

- Version(s) : 
    - 1 - 14/11/2025 : Nettoyage du fichier et création du csv "star_bus_arrets"
    - 2 - 17/11/2025 : Renommage du fichier et création du csv "stg_star_bus_arrets"

In [1]:
#Librairie(s) utilisée(s)
import pandas as pd

In [4]:
#Création du dataframe à partir du fichier csv
bus_arrets = pd.read_csv(r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\01_data\01_data_bronze\tco-bus-topologie-pointsarret-td.csv", delimiter=";")
bus_arrets.head()

,Identifiant,Date de début de version,Date de fin de version,Est la version active,Code,Nom,Commune (code INSEE),Commune (nom),Coordonnées,Accessible aux PMR,Mobilier,Visibilité,Stopid gtfs/gtfs-rt
0,1002,2024-09-02,NaN,Oui,1002,Bouzat,35238,Rennes,"48.128276, -1.637811",True,Abri simple,Grand public,6-1002
1,1012,2024-09-02,NaN,Oui,1012,Sévigné,35238,Rennes,"48.116032, -1.674241",True,Abri simple,Grand public,6-1012
2,1014,2022-10-28,NaN,Oui,1014,Bertrand,35238,Rennes,"48.113739, -1.679038",True,Poteau,Grand public,6-1014
3,1017,2024-07-08,NaN,Oui,1017,La Criée,35238,Rennes,"48.108412, -1.680208",False,Poteau,Grand public,6-1017
4,1020,2022-10-24,NaN,Oui,1020,Mermoz,35238,Rennes,"48.097428, -1.689588",True,Abri simple,Grand public,6-1020

In [5]:
# Nombre de lignes et de colonnes
bus_arrets.shape

(1820, 13)

In [6]:
# Nombre de lignes avec valeur
bus_arrets.count()

Identifiant                 1820
Date de début de version    1820
Date de fin de version        27
Est la version active       1820
Code                        1820
Nom                         1820
Commune (code INSEE)        1820
Commune (nom)               1820
Coordonnées                 1820
Accessible aux PMR          1820
Mobilier                    1786
Visibilité                  1820
Stopid gtfs/gtfs-rt         1820
dtype: int64

In [7]:
# Valeurs manquantes
bus_arrets.isnull().sum()

Identifiant                    0
Date de début de version       0
Date de fin de version      1793
Est la version active          0
Code                           0
Nom                            0
Commune (code INSEE)           0
Commune (nom)                  0
Coordonnées                    0
Accessible aux PMR             0
Mobilier                      34
Visibilité                     0
Stopid gtfs/gtfs-rt            0
dtype: int64

In [8]:
bus_arrets.columns

Index(['Identifiant', 'Date de début de version', 'Date de fin de version',
       'Est la version active', 'Code', 'Nom', 'Commune (code INSEE)',
       'Commune (nom)', 'Coordonnées', 'Accessible aux PMR', 'Mobilier',
       'Visibilité', 'Stopid gtfs/gtfs-rt'],
      dtype='object')

In [9]:
#Création de la colonne 'MVP' pour cibler les communes de la périphérie de Rennes et filtrer le dataset dessus
MVP = [35032,35058,35196,35065,35275,35144,35266,35315,35278,35245,35208,35353,35120,35210,35352,35059,35250,35079,35363,35051,35055,35076,35189,35066,35204,35022,35351,35088,35080,35131,35001,35206,35081,35139,35334,35216,35024,35240,35039,35047,35281,35180]
bus_arrets['MVP'] = bus_arrets['Commune (code INSEE)'].apply(lambda x: 'oui' if x in MVP else 'non')
bus_arrets['MVP'].describe()

count     1820
unique       2
top        oui
freq      1190
Name: MVP, dtype: object

In [10]:
#Création du mask pour filtrer le dataset sur les communes sélectionnées dans la périphérie de Rennes
mask = (bus_arrets['MVP'] == 'oui')
bus_arrets = bus_arrets[mask]

bus_arrets.shape

(1190, 14)

In [11]:
# Split de la colonne coordonnées en latitude et longitude
bus_arrets[['latitude', 'longitude']] = bus_arrets['Coordonnées'].str.split(',', expand=True)
bus_arrets.head()

,Identifiant,Date de début de version,Date de fin de version,Est la version active,Code,Nom,Commune (code INSEE),Commune (nom),Coordonnées,Accessible aux PMR,Mobilier,Visibilité,Stopid gtfs/gtfs-rt,MVP,latitude,longitude
226,2002,2024-09-02,NaN,Oui,2002,Cesson Hôpital Privé,35051,Cesson-Sévigné,"48.130225, -1.627669",True,Abri simple,Grand public,6-2002,oui,48.130225,-1.627669
228,2013,2022-10-24,NaN,Oui,2013,Vilaine,35051,Cesson-Sévigné,"48.116363, -1.607332",True,Abri simple,Grand public,6-2013,oui,48.116363,-1.607332
229,2044,2024-02-12,NaN,Oui,2044,Belle Fontaine,35051,Cesson-Sévigné,"48.127353, -1.624328",True,Abri simple,Grand public,6-2044,oui,48.127353,-1.624328
231,2045,2025-01-02,NaN,Oui,2045,Atalante,35051,Cesson-Sévigné,"48.127339, -1.628368",True,Poteau,Grand public,6-2045,oui,48.127339,-1.628368
233,2050,2024-07-08,NaN,Oui,2050,Cesson Collège,35051,Cesson-Sévigné,"48.120327, -1.599292",True,Abri simple,Grand public,6-2050,oui,48.120327,-1.599292

In [12]:
# Selection des colonnes utiles
keep_cols = ['Identifiant','Nom', 'Commune (code INSEE)','latitude', 'longitude']
df = bus_arrets.loc[:,keep_cols]
df.head()

,Identifiant,Nom,Commune (code INSEE),latitude,longitude
226,2002,Cesson Hôpital Privé,35051,48.130225,-1.627669
228,2013,Vilaine,35051,48.116363,-1.607332
229,2044,Belle Fontaine,35051,48.127353,-1.624328
231,2045,Atalante,35051,48.127339,-1.628368
233,2050,Cesson Collège,35051,48.120327,-1.599292

In [13]:
# Renommage des colonnes gardées
cols_new = ["id_arret", "nom_arret", "code_geo","latitude", "longitude"]
df.columns = cols_new
df.head()

     id_arret             nom_arret  code_geo   latitude   longitude
226      2002  Cesson Hôpital Privé     35051  48.130225   -1.627669
228      2013               Vilaine     35051  48.116363   -1.607332
229      2044        Belle Fontaine     35051  48.127353   -1.624328
231      2045              Atalante     35051  48.127339   -1.628368
233      2050        Cesson Collège     35051  48.120327   -1.599292

In [14]:
# Vérification des types des colonnes
df.dtypes

id_arret      int64
nom_arret    object
code_geo      int64
latitude     object
longitude    object
dtype: object

In [15]:
df.columns

Index(['id_arret', 'nom_arret', 'code_geo', 'latitude', 'longitude'], dtype='object')

In [17]:
# Changement de types pour certaines colonnes
df = df.astype({
    'nom_arret': 'string',
    'latitude' : 'float64',
    'longitude' : 'float64'
})
df.dtypes

id_arret              int64
nom_arret    string[python]
code_geo              int64
latitude            float64
longitude           float64
dtype: object

In [18]:
# Dernière visualisation du dataframe
df.head()

     id_arret             nom_arret  code_geo   latitude  longitude
226      2002  Cesson Hôpital Privé     35051  48.130225  -1.627669
228      2013               Vilaine     35051  48.116363  -1.607332
229      2044        Belle Fontaine     35051  48.127353  -1.624328
231      2045              Atalante     35051  48.127339  -1.628368
233      2050        Cesson Collège     35051  48.120327  -1.599292

In [19]:
print(df['id_arret'].unique())
print(df['id_arret'].nunique())

[2002 2013 2044 ... 8001 8009 8011]
1190

In [ ]:
# Export as a csv table
df.to_csv('stg_star_bus_arrets.csv', sep=';', index=False)