## Récupération des fichiers de fréquentation détaillée 2/2

- Dossier source : /data_freq_details 
- Fichier de sortie : star_freq_details.csv   
- Date de création : 14/11/2025  
- Dernière modification : 17/12/2025  
- Version(s) :  
    - 1 - 14/11/2025 : Nettoyage, filtre pour garder les données du mvp et concaténation
    - 2 - 17/12/2025 : Ajout de commentaires et markdown pour améliorer la lisibilité du notebook

Méthodologie: Travailler sur un fichier avant d'envisager de boucler afin de voir la donnée avant de faire quoi que ce soit. 👀  
Ensuite, on déterminera si on concat ou pas.

In [ ]:
#Librairie(s) utilisée(s)
import pandas as pd

In [ ]:
#Création du dataframe à partir du fichier csv
test_freq_detail= pd.read_csv(r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\02_cleaning_python\data_freq_details\csv\CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.csv",
                              delimiter= ";",
                              encoding= "UTF-8")
print(test_freq_detail.shape)
test_freq_detail.tail(10)

(779274, 9)

,DateFreq,TrancheHoraire15mn,Timeo,NomArret,NomCommune,identifiantLigne,NomCourtLigne,Sens,Frequentation
779264,31/07/2022,23:45:00,5005,Sainte-Anne,Rennes,1001.0,a,Indéterminé,"13,33333"
779265,31/07/2022,23:45:00,5006,République,Rennes,1001.0,a,Indéterminé,"21,11111"
779266,31/07/2022,23:45:00,5007,Charles de Gaulle,Rennes,1001.0,a,Indéterminé,"11,11111"
779267,31/07/2022,23:45:00,5008,Gares,Rennes,1001.0,a,Indéterminé,"7,77778"
779268,31/07/2022,23:45:00,5010,Clemenceau,Rennes,1001.0,a,Indéterminé,"3,33333"
779269,31/07/2022,23:45:00,5011,Henri Fréville,Rennes,1001.0,a,Indéterminé,"4,44444"
779270,31/07/2022,23:45:00,5012,Italie,Rennes,1001.0,a,Indéterminé,"7,77778"
779271,31/07/2022,23:45:00,5013,Triangle,Rennes,1001.0,a,Indéterminé,"3,33333"
779272,31/07/2022,23:45:00,5014,Le Blosne,Rennes,1001.0,a,Indéterminé,"1,11111"
779273,31/07/2022,23:45:00,5030,La Poterie,Rennes,1001.0,a,Indéterminé,"5,55556"

In [3]:
test_freq_detail.columns

Index(['DateFreq', 'TrancheHoraire15mn', 'Timeo', 'NomArret', 'NomCommune',
       'identifiantLigne', 'NomCourtLigne', 'Sens', 'Frequentation'],
      dtype='object')

In [4]:
test_freq_detail['NomCommune'].value_counts()

NomCommune
Rennes                        558158
Cesson-Sévigné                 30595
Saint-Jacques-de-la-Lande      26680
Saint-Grégoire                 25462
Chantepie                      16800
Bruz                           16143
Pacé                           10036
Betton                          8678
Le Rheu                         8582
Vezin-le-Coquet                 6450
Vern-sur-Seiche                 6391
Chartres-de-Bretagne            6210
Noyal-Châtillon-sur-Seiche      5825
Mordelles                       4685
Thorigné-Fouillard              4488
Non identifiée                  3937
L'Hermitage                     3464
Acigné                          3193
Montgermont                     2885
Saint-Gilles                    2608
La Chapelle-des-Fougeretz       2543
Saint-Erblon                    2310
Orgères                         2261
Pont-Péan                       2256
Gévezé                          1706
La Chapelle-Thouarault          1619
Laillé                          1514
Chavagne                        1446
Corps-Nuds                      1444
Bourgbarré                      1427
Brécé                           1424
Nouvoitou                       1315
Romillé                         1042
Cintré                          1019
Parthenay-de-Bretagne            984
Saint-Armel                      948
Chevaigné                        676
Le Verger                        526
Saint-Sulpice-la-Forêt           494
Clayes                           474
Bécherel                         228
La Chapelle-Chaussée             146
Langan                           146
Miniac-sous-Bécherel              56
Name: count, dtype: int64

In [5]:
# Filtrer NomCommune pour retirer Rennes avec mask

mask = (test_freq_detail['NomCommune'] != 'Rennes')
print(mask)

test_freq_detail_hors_rennes= test_freq_detail.loc[mask,['DateFreq', 'TrancheHoraire15mn', 'Timeo', 'NomCommune',
       'identifiantLigne', 'Sens', 'Frequentation']]
display(test_freq_detail_hors_rennes)

0         False
1         False
2         False
3         False
4         False
          ...
779269    False
779270    False
779271    False
779272    False
779273    False
Name: NomCommune, Length: 779274, dtype: bool

,DateFreq,TrancheHoraire15mn,Timeo,NomCommune,identifiantLigne,Sens,Frequentation
52,01/07/2022,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,01/07/2022,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,01/07/2022,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,01/07/2022,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,01/07/2022,00:00:00,2344,Bruz,57.0,Retour,"1,17647"
...,...,...,...,...,...,...,...
779217,31/07/2022,23:30:00,2801,Saint-Grégoire,4.0,Retour,"1,17647"
779257,31/07/2022,23:45:00,2010,Cesson-Sévigné,6.0,Aller,"2,35294"
779258,31/07/2022,23:45:00,2012,Cesson-Sévigné,6.0,Aller,"1,17647"
779259,31/07/2022,23:45:00,2015,Cesson-Sévigné,6.0,Aller,"1,17647"
779260,31/07/2022,23:45:00,2017,Cesson-Sévigné,6.0,Aller,"2,35294"

In [6]:
test_freq_detail_hors_rennes.shape

(221116, 7)

In [7]:
test_freq_detail_hors_rennes.dtypes

DateFreq               object
TrancheHoraire15mn     object
Timeo                   int64
NomCommune             object
identifiantLigne      float64
Sens                   object
Frequentation          object
dtype: object

In [9]:
# Renommer les colonnes suivants notre nomenclature:

test_freq_detail_hors_rennes.rename(columns={
    'DateFreq' : 'date', 
    'TrancheHoraire15mn' : 'tranche_horaire', 
    'Timeo' : 'id_arret', 
    'NomCommune' : 'nom_commune',
    'identifiantLigne' : 'id_ligne', 
    'Sens' : 'sens', 
    'Frequentation': 'freq'
}, inplace= True
)

test_freq_detail_hors_rennes.head()

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
52,01/07/2022,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,01/07/2022,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,01/07/2022,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,01/07/2022,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,01/07/2022,00:00:00,2344,Bruz,57.0,Retour,"1,17647"

In [10]:
test_freq_detail_hors_rennes.columns

Index(['date', 'tranche_horaire', 'id_arret', 'nom_commune', 'id_ligne',
       'sens', 'freq'],
      dtype='object')

In [11]:
test_freq_detail_hors_rennes['date'] = pd.to_datetime(test_freq_detail_hors_rennes['date'], dayfirst= True)
test_freq_detail_hors_rennes.head(30)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
52,2022-07-01,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,2022-07-01,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,2022-07-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,2022-07-01,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,2022-07-01,00:00:00,2344,Bruz,57.0,Retour,"1,17647"
57,2022-07-01,00:00:00,2344,Bruz,67.0,Retour,"1,17647"
58,2022-07-01,00:00:00,2812,Saint-Grégoire,2.0,Aller,"3,52941"
59,2022-07-01,00:00:00,2817,Saint-Grégoire,2.0,Aller,"2,35294"
60,2022-07-01,00:00:00,2842,Saint-Grégoire,2.0,Aller,"1,17647"
61,2022-07-01,00:00:00,2844,Saint-Grégoire,2.0,Retour,"1,17647"
121,2022-07-01,00:15:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
228,2022-07-01,00:45:00,2086,Cesson-Sévigné,6.0,Retour,"2,35294"
229,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Aller,"2,35294"
230,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Retour,"2,35294"
231,2022-07-01,00:45:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
232,2022-07-01,00:45:00,2241,Saint-Jacques-de-la-Lande,57.0,Aller,"1,17647"
233,2022-07-01,00:45:00,2243,Saint-Jacques-de-la-Lande,6.0,Aller,"1,17647"
234,2022-07-01,00:45:00,2801,Saint-Grégoire,4.0,Retour,"1,17647"
278,2022-07-01,01:00:00,2010,Cesson-Sévigné,6.0,Aller,"1,17647"
279,2022-07-01,01:00:00,2015,Cesson-Sévigné,6.0,Aller,"2,35294"
280,2022-07-01,01:00:00,2201,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
281,2022-07-01,01:00:00,2258,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
282,2022-07-01,01:00:00,2817,Saint-Grégoire,2.0,Aller,"1,17647"
377,2022-07-01,01:30:00,9999,Non identifiée,54.0,Aller,"1,17647"
378,2022-07-01,01:30:00,9999,Non identifiée,55.0,Aller,"1,17647"
379,2022-07-01,01:30:00,9999,Non identifiée,121.0,Retour,"10,58824"
383,2022-07-01,01:45:00,9999,Non identifiée,121.0,Retour,"4,70588"
403,2022-07-01,03:00:00,9999,Non identifiée,121.0,Retour,"4,70588"
409,2022-07-01,03:15:00,9999,Non identifiée,121.0,Retour,"2,35294"
410,2022-07-01,03:30:00,9999,Non identifiée,121.0,Retour,"2,35294"

In [12]:
test_freq_detail_hors_rennes['date'].dtypes

dtype('<M8[ns]')

In [13]:
test_freq_detail_hors_rennes['tranche_horaire'] = pd.to_datetime(test_freq_detail_hors_rennes['tranche_horaire'], format="%H:%M:%S").dt.time
test_freq_detail_hors_rennes.head(30)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
52,2022-07-01,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,2022-07-01,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,2022-07-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,2022-07-01,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,2022-07-01,00:00:00,2344,Bruz,57.0,Retour,"1,17647"
57,2022-07-01,00:00:00,2344,Bruz,67.0,Retour,"1,17647"
58,2022-07-01,00:00:00,2812,Saint-Grégoire,2.0,Aller,"3,52941"
59,2022-07-01,00:00:00,2817,Saint-Grégoire,2.0,Aller,"2,35294"
60,2022-07-01,00:00:00,2842,Saint-Grégoire,2.0,Aller,"1,17647"
61,2022-07-01,00:00:00,2844,Saint-Grégoire,2.0,Retour,"1,17647"
121,2022-07-01,00:15:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
228,2022-07-01,00:45:00,2086,Cesson-Sévigné,6.0,Retour,"2,35294"
229,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Aller,"2,35294"
230,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Retour,"2,35294"
231,2022-07-01,00:45:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
232,2022-07-01,00:45:00,2241,Saint-Jacques-de-la-Lande,57.0,Aller,"1,17647"
233,2022-07-01,00:45:00,2243,Saint-Jacques-de-la-Lande,6.0,Aller,"1,17647"
234,2022-07-01,00:45:00,2801,Saint-Grégoire,4.0,Retour,"1,17647"
278,2022-07-01,01:00:00,2010,Cesson-Sévigné,6.0,Aller,"1,17647"
279,2022-07-01,01:00:00,2015,Cesson-Sévigné,6.0,Aller,"2,35294"
280,2022-07-01,01:00:00,2201,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
281,2022-07-01,01:00:00,2258,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
282,2022-07-01,01:00:00,2817,Saint-Grégoire,2.0,Aller,"1,17647"
377,2022-07-01,01:30:00,9999,Non identifiée,54.0,Aller,"1,17647"
378,2022-07-01,01:30:00,9999,Non identifiée,55.0,Aller,"1,17647"
379,2022-07-01,01:30:00,9999,Non identifiée,121.0,Retour,"10,58824"
383,2022-07-01,01:45:00,9999,Non identifiée,121.0,Retour,"4,70588"
403,2022-07-01,03:00:00,9999,Non identifiée,121.0,Retour,"4,70588"
409,2022-07-01,03:15:00,9999,Non identifiée,121.0,Retour,"2,35294"
410,2022-07-01,03:30:00,9999,Non identifiée,121.0,Retour,"2,35294"

In [14]:
test_freq_detail_hors_rennes.dtypes

date               datetime64[ns]
tranche_horaire            object
id_arret                    int64
nom_commune                object
id_ligne                  float64
sens                       object
freq                       object
dtype: object

In [15]:
test_freq_detail_hors_rennes.isna().sum()

date                  0
tranche_horaire       0
id_arret              0
nom_commune           0
id_ligne           8585
sens                  0
freq                  0
dtype: int64

In [16]:
test_freq_detail_hors_rennes.describe()

                                date       id_arret       id_ligne
count                         221116  221116.000000  212531.000000
mean   2022-07-15 06:23:27.073210368    3402.794275     141.822129
min              2022-07-01 00:00:00    1453.000000       1.000000
25%              2022-07-07 00:00:00    2264.000000       6.000000
50%              2022-07-15 00:00:00    2812.000000      53.000000
75%              2022-07-23 00:00:00    3309.000000      62.000000
max              2022-07-31 00:00:00   65501.000000    9999.000000
std                              NaN    5309.322988     995.973218

In [17]:
# comprendre les lignes qui n'ont pas d'id_ligne

mask = test_freq_detail_hors_rennes['id_ligne'].isna()

df_id_ligne_na= test_freq_detail_hors_rennes.loc[mask,['date', 'tranche_horaire', 'id_arret', 'nom_commune', 'id_ligne',
       'sens', 'freq']]
display(df_id_ligne_na)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
823,2022-07-01,06:00:00,3903,Pont-Péan,NaN,Retour,"2,35294"
824,2022-07-01,06:00:00,3907,Pont-Péan,NaN,Retour,"1,17647"
1003,2022-07-01,06:15:00,2905,Chartres-de-Bretagne,NaN,Retour,"2,35294"
1004,2022-07-01,06:15:00,2913,Chartres-de-Bretagne,NaN,Retour,"1,17647"
1005,2022-07-01,06:15:00,2914,Chartres-de-Bretagne,NaN,Retour,"1,17647"
...,...,...,...,...,...,...,...
777961,2022-07-31,19:45:00,2905,Chartres-de-Bretagne,NaN,Retour,"1,17647"
777962,2022-07-31,19:45:00,2911,Chartres-de-Bretagne,NaN,Retour,"4,70588"
777963,2022-07-31,19:45:00,2912,Chartres-de-Bretagne,NaN,Retour,"1,17647"
777964,2022-07-31,19:45:00,2917,Chartres-de-Bretagne,NaN,Retour,"1,17647"
777975,2022-07-31,19:45:00,3907,Pont-Péan,NaN,Retour,"1,17647"

In [18]:
df_id_ligne_na.describe(include= "all")

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
count,8585,8585,8585.000000,8585,0.0,8585,8585
unique,NaN,72,NaN,12,NaN,2,21
top,NaN,17:30:00,NaN,Chartres-de-Bretagne,NaN,Retour,"1,17647"
freq,NaN,232,NaN,5657,NaN,7396,4928
mean,2022-07-15 04:24:51.158998016,NaN,3187.892836,NaN,NaN,NaN,NaN
min,2022-07-01 00:00:00,NaN,2017.000000,NaN,NaN,NaN,NaN
25%,2022-07-07 00:00:00,NaN,2907.000000,NaN,NaN,NaN,NaN
50%,2022-07-15 00:00:00,NaN,2915.000000,NaN,NaN,NaN,NaN
75%,2022-07-22 00:00:00,NaN,2944.000000,NaN,NaN,NaN,NaN
max,2022-07-31 00:00:00,NaN,65501.000000,NaN,NaN,NaN,NaN
std,NaN,NaN,2192.257718,NaN,NaN,NaN,NaN

In [19]:
# Pas d'autres valeurs manquantes et on veut collecter un max de détails sur la fréquentation / arrêt: on fait le choix de remplacer les valeurs manquantes par 0 car aucune ligne n'a l'id 0.

test_freq_detail_hors_rennes['id_ligne'] = test_freq_detail_hors_rennes['id_ligne'].fillna(0)

test_freq_detail_hors_rennes.describe()

                                date       id_arret       id_ligne
count                         221116  221116.000000  221116.000000
mean   2022-07-15 06:23:27.073210368    3402.794275     136.315775
min              2022-07-01 00:00:00    1453.000000       0.000000
25%              2022-07-07 00:00:00    2264.000000       6.000000
50%              2022-07-15 00:00:00    2812.000000      52.000000
75%              2022-07-23 00:00:00    3309.000000      61.000000
max              2022-07-31 00:00:00   65501.000000    9999.000000
std                              NaN    5309.322988     976.831288

In [20]:
test_freq_detail_hors_rennes["id_ligne"].isna().sum()

0

In [21]:
# Changement type de données (sauf [freq] qui est un cas particulier)

test_freq_detail_hors_rennes= test_freq_detail_hors_rennes.astype({
    'id_arret' : 'int64', 
    'nom_commune' : 'string', 
    'id_ligne' : 'int64',
    'sens' : 'string'
})

test_freq_detail_hors_rennes.dtypes

date               datetime64[ns]
tranche_horaire            object
id_arret                    int64
nom_commune        string[python]
id_ligne                    int64
sens               string[python]
freq                       object
dtype: object

In [22]:
# Boucle pour ouvrir les fichiers .csv, les convertir en df avec pandas et ajouter les lignes dans un seul et même df avec concat
# Ajout du mask pour garder les communes du MVP et réduire le volume de lignes
# Je vais essayer d'isoler la chaine moisannée de la date avec un split
# On décide de se concentrer sur les 12 derniers mois disponibles dans le cadre du MVP, afin de réduire le nombre de lignes

import os

chemin = r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\.old\data_freq_details\csv"

fichiers = [f for f in os.listdir(chemin) 
            if os.path.isfile(os.path.join(chemin, f))]

fichiers = sorted(fichiers, reverse=False)

LastYear = fichiers[-12:]

print(LastYear)

['CLO.FREQ.EXTRACT.FREQ-DETAIL_202409.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202410.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202411.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202412.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202501.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202502.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202503.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202504.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202505.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202506.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202507.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202508.csv']

In [23]:
colonnes= ['DateFreq', 'TrancheHoraire15mn', 'Timeo', 'NomCommune',
       'identifiantLigne', 'Sens', 'Frequentation']

colonnes_def= {
    'DateFreq' : 'date', 
    'TrancheHoraire15mn' : 'tranche_horaire', 
    'Timeo' : 'id_arret', 
    'NomCommune' : 'nom_commune',
    'identifiantLigne' : 'id_ligne', 
    'Sens' : 'sens', 
    'Frequentation': 'freq'
    }

dtypes= {
    'id_arret' : 'Int64', 
    'nom_commune' : 'string', 
    'id_ligne' : 'Int64',
    'sens' : 'string'
}

frequentations= []

for fichier in LastYear:
    
    df= pd.read_csv(
        os.path.join(chemin, fichier),
        sep= ';',
        usecols= colonnes,
        parse_dates= ['DateFreq'],
        dayfirst= True
        )
    
    df= df.rename(columns= colonnes_def)

    df= df.loc[df['nom_commune'] != 'Rennes']

    df['tranche_horaire'] = pd.to_datetime(
        df['tranche_horaire'], format="%H:%M:%S"
        ).dt.time

    df= df.astype(dtypes)
    
    frequentations.append(df)

print(frequentations[:3])

[             date tranche_horaire  id_arret                nom_commune  \
37     2024-09-01        00:00:00      2016             Cesson-Sévigné
38     2024-09-01        00:00:00      2020             Cesson-Sévigné
39     2024-09-01        00:00:00      2201  Saint-Jacques-de-la-Lande
40     2024-09-01        00:00:00      2206  Saint-Jacques-de-la-Lande
41     2024-09-01        00:00:00      2206  Saint-Jacques-de-la-Lande
...           ...             ...       ...                        ...
988854 2024-09-30        23:45:00      3751            Vezin-le-Coquet
988872 2024-09-30        23:45:00      5050             Cesson-Sévigné
988873 2024-09-30        23:45:00      5051             Cesson-Sévigné
988883 2024-09-30        23:45:00      5063  Saint-Jacques-de-la-Lande
988884 2024-09-30        23:45:00      5064  Saint-Jacques-de-la-Lande

        id_ligne         sens     freq
37             6        Aller  4,70588
38             6       Retour  1,17647
39             6       Retour  1,17647
40             6       Retour  1,17647
41            13        Aller  1,17647
...          ...          ...      ...
988854        11       Retour  1,17647
988872      1002  Indéterminé  2,22222
988873      1002  Indéterminé  2,22222
988883      1002  Indéterminé  1,11111
988884      1002  Indéterminé  0,00000

[338908 rows x 7 columns],               date tranche_horaire  id_arret                nom_commune  \
27      2024-10-01        00:00:00      2281  Saint-Jacques-de-la-Lande
28      2024-10-01        00:00:00      2801             Saint-Grégoire
46      2024-10-01        00:00:00      5050             Cesson-Sévigné
47      2024-10-01        00:00:00      5051             Cesson-Sévigné
57      2024-10-01        00:00:00      5063  Saint-Jacques-de-la-Lande
...            ...             ...       ...                        ...
1033606 2024-10-31        23:45:00      5050             Cesson-Sévigné
1033607 2024-10-31        23:45:00      5051             Cesson-Sévigné
1033617 2024-10-31        23:45:00      5063  Saint-Jacques-de-la-Lande
1033618 2024-10-31        23:45:00      5064  Saint-Jacques-de-la-Lande
1033619 2024-10-31        23:45:00      5064  Saint-Jacques-de-la-Lande

         id_ligne         sens     freq
27              7        Aller  4,70588
28              4       Retour  4,70588
46           1002  Indéterminé  5,55556
47           1002  Indéterminé  0,00000
57           1002  Indéterminé  2,22222
...           ...          ...      ...
1033606      9000  Indéterminé  7,36842
1033607      1002  Indéterminé  2,22222
1033617      1002  Indéterminé  2,22222
1033618      1002  Indéterminé  5,55556
1033619      9000  Indéterminé  6,31579

[357588 rows x 7 columns],              date tranche_horaire  id_arret                nom_commune  \
43     2024-11-01        00:00:00      2020             Cesson-Sévigné
44     2024-11-01        00:00:00      2277  Saint-Jacques-de-la-Lande
45     2024-11-01        00:00:00      2281  Saint-Jacques-de-la-Lande
46     2024-11-01        00:00:00      2801             Saint-Grégoire
47     2024-11-01        00:00:00      2809             Saint-Grégoire
...           ...             ...       ...                        ...
883154 2024-11-30        23:45:00      3002                  Chantepie
883155 2024-11-30        23:45:00      3007                  Chantepie
883158 2024-11-30        23:45:00      5050             Cesson-Sévigné
883159 2024-11-30        23:45:00      5064  Saint-Jacques-de-la-Lande
883160 2024-11-30        23:45:00     65501             Non identifiée

        id_ligne         sens      freq
43             6       Retour   1,17647
44             6       Retour   1,17647
45             7        Aller  28,23529
46             4       Retour   8,23529
47             1        Aller   1,17647
...          ...          ...       ...
883154         1       Retour   1,17647
883155         1       Retour   8,23529
883158      9000  Indéterminé   6,31579
883159      9000  Indéterminé  11,57895
883160      9999  Indéterminé   1,17647

[320816 rows x 7 columns]]

In [24]:
df_concat= pd.concat(frequentations, ignore_index= True)

print(df_concat.shape)
display(df_concat.describe(include="all"))
display(df_concat.isna().sum())

df_concat

(3813358, 7)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
count,3813358,3813358,3813318.0,3813318,3813358.0,3813358,3813358
unique,NaN,96,<NA>,43,<NA>,3,1804
top,NaN,08:00:00,<NA>,Cesson-Sévigné,<NA>,Retour,"1,17647"
freq,NaN,93811,<NA>,618799,<NA>,2148245,1644650
mean,2025-02-21 21:59:58.500848896,NaN,3323.264737,NaN,230.228558,NaN,NaN
min,2024-09-01 00:00:00,NaN,1453.0,NaN,1.0,NaN,NaN
25%,2024-11-26 00:00:00,NaN,2284.0,NaN,7.0,NaN,NaN
50%,2025-02-21 00:00:00,NaN,2812.0,NaN,53.0,NaN,NaN
75%,2025-05-20 00:00:00,NaN,3506.0,NaN,71.0,NaN,NaN
max,2025-08-31 00:00:00,NaN,65501.0,NaN,9999.0,NaN,NaN
std,NaN,NaN,4402.878785,NaN,1232.341536,NaN,NaN

date                0
tranche_horaire     0
id_arret           40
nom_commune        40
id_ligne            0
sens                0
freq                0
dtype: int64

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
0,2024-09-01,00:00:00,2016,Cesson-Sévigné,6,Aller,"4,70588"
1,2024-09-01,00:00:00,2020,Cesson-Sévigné,6,Retour,"1,17647"
2,2024-09-01,00:00:00,2201,Saint-Jacques-de-la-Lande,6,Retour,"1,17647"
3,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6,Retour,"1,17647"
4,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,13,Aller,"1,17647"
...,...,...,...,...,...,...,...
3813353,2025-08-31,23:45:00,2016,Cesson-Sévigné,6,Aller,"1,17647"
3813354,2025-08-31,23:45:00,2278,Saint-Jacques-de-la-Lande,6,Aller,"3,52941"
3813355,2025-08-31,23:45:00,5051,Cesson-Sévigné,1002,Indéterminé,"1,11111"
3813356,2025-08-31,23:45:00,5063,Saint-Jacques-de-la-Lande,1002,Indéterminé,"1,11111"
3813357,2025-08-31,23:45:00,5064,Saint-Jacques-de-la-Lande,1002,Indéterminé,"0,00000"

In [25]:
!pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\justi\anaconda3\lib\site-packages (16.1.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\justi\anaconda3\lib\site-packages (from pyarrow) (1.26.4)

In [26]:
df_concat.dtypes

date               datetime64[ns]
tranche_horaire            object
id_arret                    Int64
nom_commune        string[python]
id_ligne                    Int64
sens               string[python]
freq                       object
dtype: object

In [27]:
df_concat['freq']= df_concat['freq'].str.replace(',','.')
df_concat['freq']= df_concat['freq'].astype(float)
df_concat.dtypes

date               datetime64[ns]
tranche_horaire            object
id_arret                    Int64
nom_commune        string[python]
id_ligne                    Int64
sens               string[python]
freq                      float64
dtype: object

In [29]:
df_concat.to_csv("freq_last_year.csv", sep=";", index=False)

In [30]:
df_concat

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
0,2024-09-01,00:00:00,2016,Cesson-Sévigné,6,Aller,4.70588
1,2024-09-01,00:00:00,2020,Cesson-Sévigné,6,Retour,1.17647
2,2024-09-01,00:00:00,2201,Saint-Jacques-de-la-Lande,6,Retour,1.17647
3,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6,Retour,1.17647
4,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,13,Aller,1.17647
...,...,...,...,...,...,...,...
3813353,2025-08-31,23:45:00,2016,Cesson-Sévigné,6,Aller,1.17647
3813354,2025-08-31,23:45:00,2278,Saint-Jacques-de-la-Lande,6,Aller,3.52941
3813355,2025-08-31,23:45:00,5051,Cesson-Sévigné,1002,Indéterminé,1.11111
3813356,2025-08-31,23:45:00,5063,Saint-Jacques-de-la-Lande,1002,Indéterminé,1.11111
3813357,2025-08-31,23:45:00,5064,Saint-Jacques-de-la-Lande,1002,Indéterminé,0.00000

In [31]:
mask= (df_concat['id_arret'].isin([9235, 9236,  9237, 9238, 9242, 9243, 9245, 9246, 9247, 9248, 9249]))

print(mask)

df_concat_clean= df_concat.loc[~mask,['date', 'tranche_horaire', 'id_arret', 'nom_commune', 'id_ligne', 'sens', 'freq']]
display(df_concat_clean)

0          False
1          False
2          False
3          False
4          False
           ...
3813353    False
3813354    False
3813355    False
3813356    False
3813357    False
Name: id_arret, Length: 3813358, dtype: boolean

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
0,2024-09-01,00:00:00,2016,Cesson-Sévigné,6,Aller,4.70588
1,2024-09-01,00:00:00,2020,Cesson-Sévigné,6,Retour,1.17647
2,2024-09-01,00:00:00,2201,Saint-Jacques-de-la-Lande,6,Retour,1.17647
3,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6,Retour,1.17647
4,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,13,Aller,1.17647
...,...,...,...,...,...,...,...
3813353,2025-08-31,23:45:00,2016,Cesson-Sévigné,6,Aller,1.17647
3813354,2025-08-31,23:45:00,2278,Saint-Jacques-de-la-Lande,6,Aller,3.52941
3813355,2025-08-31,23:45:00,5051,Cesson-Sévigné,1002,Indéterminé,1.11111
3813356,2025-08-31,23:45:00,5063,Saint-Jacques-de-la-Lande,1002,Indéterminé,1.11111
3813357,2025-08-31,23:45:00,5064,Saint-Jacques-de-la-Lande,1002,Indéterminé,0.00000

Sur un volume total de 3 813 358 observations, il nous manque l'id_arret pour 40 d'entre elles.  
Je fais le choix de les remplacer par 0 pour conserver la fréquentation à l'échelle de la ligne et déterminer ensuite si cela impacte l'analyse ou non.

In [32]:
# mask pour retirer [nom_commune] 'non identifiée' ou 'null'

mask= (df_concat_clean['nom_commune'] == 'Non identifiée') | (df_concat_clean['nom_commune'].isna()) | (df_concat_clean['id_ligne'].isin([9000, 9999]))
df_concat_clean= df_concat_clean.loc[~mask,['date', 'tranche_horaire', 'id_arret', 'nom_commune', 'id_ligne', 'sens', 'freq']]

In [33]:
df_concat_clean.head()

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
0,2024-09-01,00:00:00,2016,Cesson-Sévigné,6,Aller,4.70588
1,2024-09-01,00:00:00,2020,Cesson-Sévigné,6,Retour,1.17647
2,2024-09-01,00:00:00,2201,Saint-Jacques-de-la-Lande,6,Retour,1.17647
3,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6,Retour,1.17647
4,2024-09-01,00:00:00,2206,Saint-Jacques-de-la-Lande,13,Aller,1.17647

In [34]:
df_concat_clean.isna().sum()

date               0
tranche_horaire    0
id_arret           0
nom_commune        0
id_ligne           0
sens               0
freq               0
dtype: int64

In [35]:
df_concat_clean.to_csv("star_freq_details.csv", sep=';', index=False)

In [36]:
df_concat_clean.shape

(3717597, 7)

In [37]:
df_concat['id_ligne']= df_concat['id_ligne'].fillna(0)
display(df_concat.describe(include= "all"))

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
count,3813358,3813358,3813318.0,3813318,3813358.0,3813358,3.813358e+06
unique,NaN,96,<NA>,43,<NA>,3,NaN
top,NaN,08:00:00,<NA>,Cesson-Sévigné,<NA>,Retour,NaN
freq,NaN,93811,<NA>,618799,<NA>,2148245,NaN
mean,2025-02-21 21:59:58.500848896,NaN,3323.264737,NaN,230.228558,NaN,4.623618e+00
min,2024-09-01 00:00:00,NaN,1453.0,NaN,1.0,NaN,0.000000e+00
25%,2024-11-26 00:00:00,NaN,2284.0,NaN,7.0,NaN,1.176470e+00
50%,2025-02-21 00:00:00,NaN,2812.0,NaN,53.0,NaN,2.352940e+00
75%,2025-05-20 00:00:00,NaN,3506.0,NaN,71.0,NaN,3.529410e+00
max,2025-08-31 00:00:00,NaN,65501.0,NaN,9999.0,NaN,2.182353e+03
std,NaN,NaN,4402.878785,NaN,1232.341536,NaN,2.000643e+01