## Récupération des fichiers de fréquentation détaillée 1/2

- Fichier source : tco-billettique-frequentation-detaillee-td.csv  
Compile des liens URL redirigeant vers d'autres fichiers (un par mois)  
- Dossier de sortie : /data_freq_details  
- Date de création : 14/11/2025  
- Dernière modification : 17/12/2025  
- Version(s) :  
    - 1 - 14/11/2025 : Récupération des csv et rangement dans /data_freq_details 
    - 2 - 17/12/2025 : Ajout de commentaires et markdown pour améliorer la lisibilité du notebook

In [1]:
#Librairie(s) utilisée(s)
import pandas as pd

In [ ]:
#Création du dataframe à partir du fichier csv
df= pd.read_csv(r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\01_data\01_data_bronze\tco-billettique-frequentation-detaillee-td.csv",
                                   delimiter= ";")
df.head()

,ID,Fichier,URL,Taille (en octets),decription,dateDebut,dateFin,dateMiseDisponibilite
0,CLO.FREQ.EXTRACT.FREQ-DETAIL_202205,https://data.explore.star.fr/api/explore/v2.1/...,https://eu.ftp.opendatasoft.com/star/billettiq...,10104051,Données de fréquentation agrégées des lignes d...,2022-05-01,2022-05-31,2022-09-09T18:40:50+02:00
1,CLO.FREQ.EXTRACT.FREQ-DETAIL_202206,https://data.explore.star.fr/api/explore/v2.1/...,https://eu.ftp.opendatasoft.com/star/billettiq...,9642846,Données de fréquentation agrégées des lignes d...,2022-06-01,2022-06-30,2022-09-09T18:40:50+02:00
2,CLO.FREQ.EXTRACT.FREQ-DETAIL_202301,https://data.explore.star.fr/api/explore/v2.1/...,https://eu.ftp.opendatasoft.com/star/billettiq...,10577141,Données de fréquentation agrégées des lignes d...,2023-01-01,2023-01-31,2023-03-05T21:00:24+01:00
3,CLO.FREQ.EXTRACT.FREQ-DETAIL_202302,https://data.explore.star.fr/api/explore/v2.1/...,https://eu.ftp.opendatasoft.com/star/billettiq...,9235978,Données de fréquentation agrégées des lignes d...,2023-02-01,2023-02-28,2023-04-05T22:00:23+02:00
4,CLO.FREQ.EXTRACT.FREQ-DETAIL_202408,https://data.explore.star.fr/api/explore/v2.1/...,https://eu.ftp.opendatasoft.com/star/billettiq...,7344977,Données de fréquentation agrégées des lignes d...,2024-08-01,2024-08-31,2024-10-05T22:00:26+02:00

In [ ]:
# Boucle pour activer les liens url et lancer le téléchargement du fichier détaillé
# Objectif: enregistrer les fichiers .csv dans un même sous-dossier

# 1. enregistrer les url dans une liste
liste_url= df["URL"].tolist()
print(liste_url)

# 2. enregistrer les fichiers .zip dans le sous-dossier data_freq_details
import requests
import os

dossier= r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\02_cleaning_python\data_freq_details"

for url in liste_url:
    nom_fichier= os.path.basename(url)
    chemin_complet= os.path.join(dossier, nom_fichier)
    print(f"Téléchargement de {nom_fichier}...")

    fichier= requests.get(url)
    if fichier.status_code == 200:
        with open(chemin_complet, "wb") as f:       # ouvre le fichier en sachant qu'il va devoir écrire ("w") dedans et que c'est du binaire ("b")
            f.write(fichier.content)                # écrit dans le fichier qu'il a ouvert, le contenu du fichier téléchargé
        print(f"...{nom_fichier} enregistré dans {dossier}.")
    else:
        print(f"Erreur {fichier.status_code} pour {url}.")

['https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202205.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202206.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202301.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202302.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202408.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202410.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202202.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202209.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202312.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202402.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202409.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202505.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202204.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202201.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202303.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202307.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202309.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202401.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202403.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202404.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202411.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202203.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202211.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202212.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202305.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202306.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202310.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202311.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202406.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202407.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202501.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202502.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202503.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202504.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202208.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202210.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202304.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202308.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202412.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202506.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202507.zip', 'https://eu.ftp.opendatasoft.com/star/billettique/frequentation/detaillee/CLO.FREQ.EXTRACT.FREQ-DETAIL_202508.zip']
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202205.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202205.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202206.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202206.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202301.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202301.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202302.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202302.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202408.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202408.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202410.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202410.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202202.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202202.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202209.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202209.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202312.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202312.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202402.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202402.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202409.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202409.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202505.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202505.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202204.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202204.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202201.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202201.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202303.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202303.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202307.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202307.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202309.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202309.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202401.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202401.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202403.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202403.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202404.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202404.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202411.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202411.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202203.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202203.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202211.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202211.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202212.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202212.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202305.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202305.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202306.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202306.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202310.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202310.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202311.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202311.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202406.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202406.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202407.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202407.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202501.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202501.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202502.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202502.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202503.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202503.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202504.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202504.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202208.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202208.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202210.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202210.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202304.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202304.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202308.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202308.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202412.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202412.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202506.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202506.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202507.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202507.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.
Téléchargement de CLO.FREQ.EXTRACT.FREQ-DETAIL_202508.zip...
...CLO.FREQ.EXTRACT.FREQ-DETAIL_202508.zip enregistré dans C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details.

In [ ]:
# Boucle pour dézipper les .zip

import zipfile
import glob

# Définir les chemins:
dossier_avec_zip= r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details"
dossier_destination= r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\csv"

# Trouver tous les fichiers .zip dans le dossier:
fichiers_zip= glob.glob(f"{dossier_avec_zip}/*.zip")    # j'ajoute / pour que le chemin fonctionne
                                                        # la bonne pratique serait d'utiliser os.path.join 

if not fichiers_zip:
    print(f"Aucun fichier .zip trouvé dans le dossier : {dossier_avec_zip}")
else:
    print(f"{len(fichiers_zip)} fichiers .zip trouvés. Début de l'extraction...")   # Permet de savoir si Python trouve les fichiers

# Boucle sur chaque fichier pour l'extraire:
    for fichier in fichiers_zip:
        with zipfile.ZipFile(fichier, "r") as zip_ref:      #'r' to read an existing file
            zip_ref.extractall(dossier_destination)
            print(f"Extrait {fichier} ok.")

43 fichiers .zip trouvés. Début de l'extraction...
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202201.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202202.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202203.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202204.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202205.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202206.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202208.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202209.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202210.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202211.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202212.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202301.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202302.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202303.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202304.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202305.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202306.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202307.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202308.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202309.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202310.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202311.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202312.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202401.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202402.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202403.zip ok.

BadZipFile: File is not a zip file

In [12]:
# la boucle s'arrête du fait d'une erreur, je recommence avec un Try/Except

import zipfile
import glob

dossier_avec_zip= r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details"
dossier_destination= r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\csv"

fichiers_zip= glob.glob(f"{dossier_avec_zip}/*.zip")    

if not fichiers_zip:
    print(f"Aucun fichier .zip trouvé dans le dossier : {dossier_avec_zip}")
else:
    print(f"{len(fichiers_zip)} fichiers .zip trouvés. Début de l'extraction...")   

# Boucle sur chaque fichier pour l'extraire:
    for fichier in fichiers_zip:
        try:
            with zipfile.ZipFile(fichier, "r") as zip_ref:      #'r' to read an existing file
                zip_ref.extractall(dossier_destination)
                print(f"Extrait {fichier} ok.")
        
        except zipfile.BadZipFile:
            print(f"ERREUR: le fichier {fichier} est corrompu ou n'est pas un fichier zip valide.")
        except Exception:
            print(f"ERREUR lors du traitement de {fichier}: {Exception}")

print("Processus de dézippage terminé.")

43 fichiers .zip trouvés. Début de l'extraction...
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202201.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202202.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202203.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202204.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202205.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202206.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202208.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202209.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202210.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202211.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202212.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202301.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202302.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202303.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202304.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202305.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202306.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202307.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202308.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202309.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202310.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202311.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202312.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202401.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202402.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202403.zip ok.
ERREUR: le fichier C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202404.zip est corrompu ou n'est pas un fichier zip valide.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202406.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202407.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202408.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202409.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202410.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202411.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202412.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202501.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202502.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202503.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202504.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202505.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202506.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202507.zip ok.
Extrait C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\2_Fullstack\11_final_project\data_freq_details\CLO.FREQ.EXTRACT.FREQ-DETAIL_202508.zip ok.
Processus de dézippage terminé.

Enorme volume de lignes, surtout si on fait x42.  
On fait le choix de travailler avec les données des 12 derniers mois pour couvrir une année entière pour le MVP.

In [ ]:
# Boucle pour ouvrir les fichiers .csv, les convertir en df avec pandas et ajouter les lignes dans un seul et même df avec concat
# Ajout du mask pour garder uniquement les communes du MVP et réduire le volume de lignes
# Je vais essayer d'isoler la chaine moisannée de la date avec un split

import os

chemin = r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\02_cleaning_python\data_freq_details\csv"

fichiers = [f for f in os.listdir(chemin) 
            if os.path.isfile(os.path.join(chemin, f))]

fichiers = sorted(fichiers, reverse=True)

LastYear = fichiers[-12:]

print(LastYear[:3])

frequentations= []

for fichier in LastYear:
    df= pd.read_csv(fichier, sep= ';')
    mask= (df['NomCommune'] != 'Rennes')
    df= df.loc([mask],['DateFreq', 'TrancheHoraire15mn', 'Timeo', 'NomArret', 'NomCommune',
       'identifiantLigne', 'NomCourtLigne', 'Sens', 'Frequentation'])
    df.rename(columns={
    'DateFreq' : 'date', 
    'TrancheHoraire15mn' : 'tranche_horaire', 
    'Timeo' : 'id_arret', 
    'NomCommune' : 'nom_commune',
    'identifiantLigne' : 'id_ligne', 
    'Sens' : 'sens', 
    'Frequentation': 'freq'
    }, inplace= True)
    df['date'] = pd.to_datetime(df['date'], dayfirst= True)
    df['tranche_horaire'] = pd.to_datetime(df['tranche_horaire'], format="%H:%M:%S").dt.time
    df= df.astype({
    'id_arret' : 'int64', 
    'nom_commune' : 'string', 
    'id_ligne' : 'int64',
    'sens' : 'string'
    })
    frequentations.append(df)

print(frequentations[:3])

['CLO.FREQ.EXTRACT.FREQ-DETAIL_202302.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202301.csv', 'CLO.FREQ.EXTRACT.FREQ-DETAIL_202212.csv']

Méthodologie: Travailler sur un fichier avant d'envisager de boucler afin de voir la donnée avant de faire quoi que ce soit. 👀  
Ensuite, on déterminera si on concat ou pas.

In [ ]:
test_freq_detail= pd.read_csv(r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\02_cleaning_python\data_freq_details\csv\CLO.FREQ.EXTRACT.FREQ-DETAIL_202207.csv",
                              delimiter= ";",
                              encoding= "UTF-8")
print(test_freq_detail.shape)
test_freq_detail.tail(10)

(779274, 9)

,DateFreq,TrancheHoraire15mn,Timeo,NomArret,NomCommune,identifiantLigne,NomCourtLigne,Sens,Frequentation
779264,31/07/2022,23:45:00,5005,Sainte-Anne,Rennes,1001.0,a,Indéterminé,"13,33333"
779265,31/07/2022,23:45:00,5006,République,Rennes,1001.0,a,Indéterminé,"21,11111"
779266,31/07/2022,23:45:00,5007,Charles de Gaulle,Rennes,1001.0,a,Indéterminé,"11,11111"
779267,31/07/2022,23:45:00,5008,Gares,Rennes,1001.0,a,Indéterminé,"7,77778"
779268,31/07/2022,23:45:00,5010,Clemenceau,Rennes,1001.0,a,Indéterminé,"3,33333"
779269,31/07/2022,23:45:00,5011,Henri Fréville,Rennes,1001.0,a,Indéterminé,"4,44444"
779270,31/07/2022,23:45:00,5012,Italie,Rennes,1001.0,a,Indéterminé,"7,77778"
779271,31/07/2022,23:45:00,5013,Triangle,Rennes,1001.0,a,Indéterminé,"3,33333"
779272,31/07/2022,23:45:00,5014,Le Blosne,Rennes,1001.0,a,Indéterminé,"1,11111"
779273,31/07/2022,23:45:00,5030,La Poterie,Rennes,1001.0,a,Indéterminé,"5,55556"

In [156]:
test_freq_detail.columns

Index(['DateFreq', 'TrancheHoraire15mn', 'Timeo', 'NomArret', 'NomCommune',
       'identifiantLigne', 'NomCourtLigne', 'Sens', 'Frequentation'],
      dtype='object')

In [157]:
test_freq_detail['NomCommune'].value_counts()

NomCommune
Rennes                        558158
Cesson-Sévigné                 30595
Saint-Jacques-de-la-Lande      26680
Saint-Grégoire                 25462
Chantepie                      16800
Bruz                           16143
Pacé                           10036
Betton                          8678
Le Rheu                         8582
Vezin-le-Coquet                 6450
Vern-sur-Seiche                 6391
Chartres-de-Bretagne            6210
Noyal-Châtillon-sur-Seiche      5825
Mordelles                       4685
Thorigné-Fouillard              4488
Non identifiée                  3937
L'Hermitage                     3464
Acigné                          3193
Montgermont                     2885
Saint-Gilles                    2608
La Chapelle-des-Fougeretz       2543
Saint-Erblon                    2310
Orgères                         2261
Pont-Péan                       2256
Gévezé                          1706
La Chapelle-Thouarault          1619
Laillé                          1514
Chavagne                        1446
Corps-Nuds                      1444
Bourgbarré                      1427
Brécé                           1424
Nouvoitou                       1315
Romillé                         1042
Cintré                          1019
Parthenay-de-Bretagne            984
Saint-Armel                      948
Chevaigné                        676
Le Verger                        526
Saint-Sulpice-la-Forêt           494
Clayes                           474
Bécherel                         228
La Chapelle-Chaussée             146
Langan                           146
Miniac-sous-Bécherel              56
Name: count, dtype: int64

In [ ]:
# Filtrer NomCommune pour retirer Rennes avec mask

mask = (test_freq_detail['NomCommune'] != 'Rennes')
print(mask)

test_freq_detail_hors_rennes= test_freq_detail.loc[mask,['DateFreq', 'TrancheHoraire15mn', 'Timeo', 'NomCommune',
       'identifiantLigne', 'Sens', 'Frequentation']]
display(test_freq_detail_hors_rennes)

0         False
1         False
2         False
3         False
4         False
          ...
779269    False
779270    False
779271    False
779272    False
779273    False
Name: NomCommune, Length: 779274, dtype: bool

,DateFreq,TrancheHoraire15mn,Timeo,NomArret,NomCommune,identifiantLigne,NomCourtLigne,Sens,Frequentation
52,01/07/2022,00:00:00,2016,Taillis,Cesson-Sévigné,6.0,C6,Aller,"1,17647"
53,01/07/2022,00:00:00,2017,Champs Péans,Cesson-Sévigné,6.0,C6,Aller,"1,17647"
54,01/07/2022,00:00:00,2206,Gaité,Saint-Jacques-de-la-Lande,6.0,C6,Retour,"1,17647"
55,01/07/2022,00:00:00,2343,Epalet,Bruz,57.0,57,Retour,"2,35294"
56,01/07/2022,00:00:00,2344,Noë,Bruz,57.0,57,Retour,"1,17647"
...,...,...,...,...,...,...,...,...,...
779217,31/07/2022,23:30:00,2801,Grand Quartier,Saint-Grégoire,4.0,C4,Retour,"1,17647"
779257,31/07/2022,23:45:00,2010,Mare Pavée,Cesson-Sévigné,6.0,C6,Aller,"2,35294"
779258,31/07/2022,23:45:00,2012,Muguet,Cesson-Sévigné,6.0,C6,Aller,"1,17647"
779259,31/07/2022,23:45:00,2015,Hublais,Cesson-Sévigné,6.0,C6,Aller,"1,17647"
779260,31/07/2022,23:45:00,2017,Champs Péans,Cesson-Sévigné,6.0,C6,Aller,"2,35294"

In [159]:
test_freq_detail_hors_rennes.shape

(221116, 9)

In [160]:
test_freq_detail_hors_rennes.dtypes

DateFreq               object
TrancheHoraire15mn     object
Timeo                   int64
NomArret               object
NomCommune             object
identifiantLigne      float64
NomCourtLigne          object
Sens                   object
Frequentation          object
dtype: object

In [161]:
# Drop des colonnes NomArret et NomCourtLigne car pas utile. Il faudra dropper NomCommune en toute fin. Je la garde pour l'instant.

test_freq_detail_hors_rennes= test_freq_detail_hors_rennes.drop(columns= ['NomArret', 'NomCourtLigne'])
test_freq_detail_hors_rennes.head()

,DateFreq,TrancheHoraire15mn,Timeo,NomCommune,identifiantLigne,Sens,Frequentation
52,01/07/2022,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,01/07/2022,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,01/07/2022,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,01/07/2022,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,01/07/2022,00:00:00,2344,Bruz,57.0,Retour,"1,17647"

In [ ]:
# Renommer les colonnes suivant notre nomenclature:

test_freq_detail_hors_rennes.rename(columns={
    'DateFreq' : 'date', 
    'TrancheHoraire15mn' : 'tranche_horaire', 
    'Timeo' : 'id_arret', 
    'NomCommune' : 'nom_commune',
    'identifiantLigne' : 'id_ligne', 
    'Sens' : 'sens', 
    'Frequentation': 'freq'
}, inplace= True
)

test_freq_detail_hors_rennes.head()

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
52,01/07/2022,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,01/07/2022,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,01/07/2022,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,01/07/2022,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,01/07/2022,00:00:00,2344,Bruz,57.0,Retour,"1,17647"

In [163]:
test_freq_detail_hors_rennes.columns

Index(['date', 'tranche_horaire', 'id_arret', 'nom_commune', 'id_ligne',
       'sens', 'freq'],
      dtype='object')

In [164]:
test_freq_detail_hors_rennes['date'] = pd.to_datetime(test_freq_detail_hors_rennes['date'], dayfirst= True)
test_freq_detail_hors_rennes.head(30)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
52,2022-07-01,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,2022-07-01,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,2022-07-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,2022-07-01,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,2022-07-01,00:00:00,2344,Bruz,57.0,Retour,"1,17647"
57,2022-07-01,00:00:00,2344,Bruz,67.0,Retour,"1,17647"
58,2022-07-01,00:00:00,2812,Saint-Grégoire,2.0,Aller,"3,52941"
59,2022-07-01,00:00:00,2817,Saint-Grégoire,2.0,Aller,"2,35294"
60,2022-07-01,00:00:00,2842,Saint-Grégoire,2.0,Aller,"1,17647"
61,2022-07-01,00:00:00,2844,Saint-Grégoire,2.0,Retour,"1,17647"
121,2022-07-01,00:15:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
228,2022-07-01,00:45:00,2086,Cesson-Sévigné,6.0,Retour,"2,35294"
229,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Aller,"2,35294"
230,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Retour,"2,35294"
231,2022-07-01,00:45:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
232,2022-07-01,00:45:00,2241,Saint-Jacques-de-la-Lande,57.0,Aller,"1,17647"
233,2022-07-01,00:45:00,2243,Saint-Jacques-de-la-Lande,6.0,Aller,"1,17647"
234,2022-07-01,00:45:00,2801,Saint-Grégoire,4.0,Retour,"1,17647"
278,2022-07-01,01:00:00,2010,Cesson-Sévigné,6.0,Aller,"1,17647"
279,2022-07-01,01:00:00,2015,Cesson-Sévigné,6.0,Aller,"2,35294"
280,2022-07-01,01:00:00,2201,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
281,2022-07-01,01:00:00,2258,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
282,2022-07-01,01:00:00,2817,Saint-Grégoire,2.0,Aller,"1,17647"
377,2022-07-01,01:30:00,9999,Non identifiée,54.0,Aller,"1,17647"
378,2022-07-01,01:30:00,9999,Non identifiée,55.0,Aller,"1,17647"
379,2022-07-01,01:30:00,9999,Non identifiée,121.0,Retour,"10,58824"
383,2022-07-01,01:45:00,9999,Non identifiée,121.0,Retour,"4,70588"
403,2022-07-01,03:00:00,9999,Non identifiée,121.0,Retour,"4,70588"
409,2022-07-01,03:15:00,9999,Non identifiée,121.0,Retour,"2,35294"
410,2022-07-01,03:30:00,9999,Non identifiée,121.0,Retour,"2,35294"

In [165]:
test_freq_detail_hors_rennes['date'].dtypes

dtype('<M8[ns]')

In [166]:
test_freq_detail_hors_rennes['tranche_horaire'] = pd.to_datetime(test_freq_detail_hors_rennes['tranche_horaire'], format="%H:%M:%S").dt.time
test_freq_detail_hors_rennes.head(30)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
52,2022-07-01,00:00:00,2016,Cesson-Sévigné,6.0,Aller,"1,17647"
53,2022-07-01,00:00:00,2017,Cesson-Sévigné,6.0,Aller,"1,17647"
54,2022-07-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
55,2022-07-01,00:00:00,2343,Bruz,57.0,Retour,"2,35294"
56,2022-07-01,00:00:00,2344,Bruz,57.0,Retour,"1,17647"
57,2022-07-01,00:00:00,2344,Bruz,67.0,Retour,"1,17647"
58,2022-07-01,00:00:00,2812,Saint-Grégoire,2.0,Aller,"3,52941"
59,2022-07-01,00:00:00,2817,Saint-Grégoire,2.0,Aller,"2,35294"
60,2022-07-01,00:00:00,2842,Saint-Grégoire,2.0,Aller,"1,17647"
61,2022-07-01,00:00:00,2844,Saint-Grégoire,2.0,Retour,"1,17647"
121,2022-07-01,00:15:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
228,2022-07-01,00:45:00,2086,Cesson-Sévigné,6.0,Retour,"2,35294"
229,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Aller,"2,35294"
230,2022-07-01,00:45:00,2089,Cesson-Sévigné,6.0,Retour,"2,35294"
231,2022-07-01,00:45:00,2126,Cesson-Sévigné,1.0,Aller,"1,17647"
232,2022-07-01,00:45:00,2241,Saint-Jacques-de-la-Lande,57.0,Aller,"1,17647"
233,2022-07-01,00:45:00,2243,Saint-Jacques-de-la-Lande,6.0,Aller,"1,17647"
234,2022-07-01,00:45:00,2801,Saint-Grégoire,4.0,Retour,"1,17647"
278,2022-07-01,01:00:00,2010,Cesson-Sévigné,6.0,Aller,"1,17647"
279,2022-07-01,01:00:00,2015,Cesson-Sévigné,6.0,Aller,"2,35294"
280,2022-07-01,01:00:00,2201,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
281,2022-07-01,01:00:00,2258,Saint-Jacques-de-la-Lande,6.0,Retour,"1,17647"
282,2022-07-01,01:00:00,2817,Saint-Grégoire,2.0,Aller,"1,17647"
377,2022-07-01,01:30:00,9999,Non identifiée,54.0,Aller,"1,17647"
378,2022-07-01,01:30:00,9999,Non identifiée,55.0,Aller,"1,17647"
379,2022-07-01,01:30:00,9999,Non identifiée,121.0,Retour,"10,58824"
383,2022-07-01,01:45:00,9999,Non identifiée,121.0,Retour,"4,70588"
403,2022-07-01,03:00:00,9999,Non identifiée,121.0,Retour,"4,70588"
409,2022-07-01,03:15:00,9999,Non identifiée,121.0,Retour,"2,35294"
410,2022-07-01,03:30:00,9999,Non identifiée,121.0,Retour,"2,35294"

In [167]:
test_freq_detail_hors_rennes.dtypes

date               datetime64[ns]
tranche_horaire            object
id_arret                    int64
nom_commune                object
id_ligne                  float64
sens                       object
freq                       object
dtype: object

In [168]:
test_freq_detail_hors_rennes.isna().sum()

date                  0
tranche_horaire       0
id_arret              0
nom_commune           0
id_ligne           8585
sens                  0
freq                  0
dtype: int64

In [169]:
test_freq_detail_hors_rennes.describe()

                                date       id_arret       id_ligne
count                         221116  221116.000000  212531.000000
mean   2022-07-15 06:23:27.073210368    3402.794275     141.822129
min              2022-07-01 00:00:00    1453.000000       1.000000
25%              2022-07-07 00:00:00    2264.000000       6.000000
50%              2022-07-15 00:00:00    2812.000000      53.000000
75%              2022-07-23 00:00:00    3309.000000      62.000000
max              2022-07-31 00:00:00   65501.000000    9999.000000
std                              NaN    5309.322988     995.973218

In [170]:
# comprendre les lignes qui n'ont pas d'id_ligne

mask = test_freq_detail_hors_rennes['id_ligne'].isna()

df_id_ligne_na= test_freq_detail_hors_rennes.loc[mask,['date', 'tranche_horaire', 'id_arret', 'nom_commune', 'id_ligne',
       'sens', 'freq']]
display(df_id_ligne_na)

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
823,2022-07-01,06:00:00,3903,Pont-Péan,NaN,Retour,"2,35294"
824,2022-07-01,06:00:00,3907,Pont-Péan,NaN,Retour,"1,17647"
1003,2022-07-01,06:15:00,2905,Chartres-de-Bretagne,NaN,Retour,"2,35294"
1004,2022-07-01,06:15:00,2913,Chartres-de-Bretagne,NaN,Retour,"1,17647"
1005,2022-07-01,06:15:00,2914,Chartres-de-Bretagne,NaN,Retour,"1,17647"
...,...,...,...,...,...,...,...
777961,2022-07-31,19:45:00,2905,Chartres-de-Bretagne,NaN,Retour,"1,17647"
777962,2022-07-31,19:45:00,2911,Chartres-de-Bretagne,NaN,Retour,"4,70588"
777963,2022-07-31,19:45:00,2912,Chartres-de-Bretagne,NaN,Retour,"1,17647"
777964,2022-07-31,19:45:00,2917,Chartres-de-Bretagne,NaN,Retour,"1,17647"
777975,2022-07-31,19:45:00,3907,Pont-Péan,NaN,Retour,"1,17647"

In [171]:
df_id_ligne_na.describe(include= "all")

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq
count,8585,8585,8585.000000,8585,0.0,8585,8585
unique,NaN,72,NaN,12,NaN,2,21
top,NaN,17:30:00,NaN,Chartres-de-Bretagne,NaN,Retour,"1,17647"
freq,NaN,232,NaN,5657,NaN,7396,4928
mean,2022-07-15 04:24:51.158998016,NaN,3187.892836,NaN,NaN,NaN,NaN
min,2022-07-01 00:00:00,NaN,2017.000000,NaN,NaN,NaN,NaN
25%,2022-07-07 00:00:00,NaN,2907.000000,NaN,NaN,NaN,NaN
50%,2022-07-15 00:00:00,NaN,2915.000000,NaN,NaN,NaN,NaN
75%,2022-07-22 00:00:00,NaN,2944.000000,NaN,NaN,NaN,NaN
max,2022-07-31 00:00:00,NaN,65501.000000,NaN,NaN,NaN,NaN
std,NaN,NaN,2192.257718,NaN,NaN,NaN,NaN

In [172]:
# Pas d'autres valeurs manquantes et on veut collecter un max de détails sur la fréquentation / arrêt: on fait le choix de remplacer les valeurs manquantes par 0 car aucune ligne n'a l'id 0.

test_freq_detail_hors_rennes['id_ligne'] = test_freq_detail_hors_rennes['id_ligne'].fillna(0)

test_freq_detail_hors_rennes.describe()

                                date       id_arret       id_ligne
count                         221116  221116.000000  221116.000000
mean   2022-07-15 06:23:27.073210368    3402.794275     136.315775
min              2022-07-01 00:00:00    1453.000000       0.000000
25%              2022-07-07 00:00:00    2264.000000       6.000000
50%              2022-07-15 00:00:00    2812.000000      52.000000
75%              2022-07-23 00:00:00    3309.000000      61.000000
max              2022-07-31 00:00:00   65501.000000    9999.000000
std                              NaN    5309.322988     976.831288

In [173]:
test_freq_detail_hors_rennes["id_ligne"].isna().sum()

0

In [174]:
# Changement type de données (sauf [freq] qui est un cas particulier)

test_freq_detail_hors_rennes= test_freq_detail_hors_rennes.astype({
    'id_arret' : 'int64', 
    'nom_commune' : 'string', 
    'id_ligne' : 'int64',
    'sens' : 'string'
})

test_freq_detail_hors_rennes.dtypes

date               datetime64[ns]
tranche_horaire            object
id_arret                    int64
nom_commune        string[python]
id_ligne                    int64
sens               string[python]
freq                       object
dtype: object

In [176]:
# Création de la colonne id_ligne_id_arret:

test_freq_detail_hors_rennes['id_ligne_id_arret']= test_freq_detail_hors_rennes['id_ligne'].astype(str) + '_' + test_freq_detail_hors_rennes['id_arret'].astype(str)

test_freq_detail_hors_rennes.head()

,date,tranche_horaire,id_arret,nom_commune,id_ligne,sens,freq,id_ligne_id_arret
52,2022-07-01,00:00:00,2016,Cesson-Sévigné,6,Aller,"1,17647",6_2016
53,2022-07-01,00:00:00,2017,Cesson-Sévigné,6,Aller,"1,17647",6_2017
54,2022-07-01,00:00:00,2206,Saint-Jacques-de-la-Lande,6,Retour,"1,17647",6_2206
55,2022-07-01,00:00:00,2343,Bruz,57,Retour,"2,35294",57_2343
56,2022-07-01,00:00:00,2344,Bruz,57,Retour,"1,17647",57_2344